export enum LIST_TYPES {
	UPDATE_LIST = 'UPDATE_LIST',
	ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST',
	REMOVE_ITEM_FROM_LIST = 'REMOVE_ITEM_FROM_LIST',
	SET_COMPLETE_ITEM = 'SET_COMPLETE_ITEM',
	TOGGLE_DETAILED = 'TOGGLE_DETAILED',
}
