export enum USER_TYPES {
	SET_CURRENT_USER = 'SET_CURRENT_USER',
	SIGN_UP_START = 'SIGN_UP_START',
	SIGN_UP_FAILED = 'SIGN_UP_FAILED',
	SIGN_IN_START = 'SIGN_IN_START',
	SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILED = 'SIGN_IN_FAILED',
	SIGN_OUT = 'SIGN_OUT',
}
