export enum TIMER_TYPES {
	SET_IS_COUNTING = 'SET_IS_COUNTING',
	ON_TIMER_START = 'ON_TIMER_START',
	ON_TIMER_COUNT = 'ON_TIMER_COUNT',
	ON_TIMER_STOP = 'ON_TIMER_STOP',
	RESET_TIMER = 'RESET_TIMER',
	SET_START_TIME = 'SET_START_TIME',
	SET_DEFAULT_TIME = 'SET_DEFAULT_TIME',
}
